# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-15 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('mdate', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('data', models.TextField(blank=True, null=True)),
                ('loaded', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExchangePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('mdate', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
                ('data', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('loaded', models.BooleanField(default=False)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loader.Exchange')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PriceError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('mdate', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
                ('symbolname', models.CharField(db_index=True, max_length=10, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
