# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-18 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeSplit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('mdate', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
                ('data', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('loaded', models.BooleanField(default=False)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loader.Exchange')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
