# Generated by Django 3.1.4 on 2020-12-30 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Split',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ratio', models.CharField(max_length=10)),
                ('applied', models.BooleanField(db_index=True, default=False)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aim.symbol')),
            ],
        ),
    ]
