# Generated by Django 3.1.4 on 2020-12-30 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aim', '0003_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shares', models.DecimalField(decimal_places=3, max_digits=10)),
                ('price', models.DecimalField(decimal_places=3, max_digits=8)),
                ('type', models.CharField(choices=[('Buy', 'Buy Shares'), ('Sell', 'Sell Shares')], default='Buy', max_length=10)),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aim.holding')),
            ],
        ),
        migrations.CreateModel(
            name='HoldingAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('buyprice', models.DecimalField(decimal_places=3, max_digits=10)),
                ('sellprice', models.DecimalField(decimal_places=3, max_digits=10)),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aim.holding')),
            ],
        ),
        migrations.AddField(
            model_name='holding',
            name='currentalert',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='alertholding', to='aim.holdingalert'),
        ),
        migrations.AddField(
            model_name='holding',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aim.portfolio'),
        ),
        migrations.AddField(
            model_name='holding',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aim.symbol'),
        ),
        migrations.CreateModel(
            name='AimController',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.BooleanField(default=False)),
                ('control', models.IntegerField(default=0)),
                ('sellsafe', models.IntegerField(default=10)),
                ('buysafe', models.IntegerField(default=10)),
                ('buymin', models.IntegerField(default=500)),
                ('sellmin', models.IntegerField(default=500)),
                ('buyperc', models.IntegerField(default=10)),
                ('sellperc', models.IntegerField(default=10)),
                ('holding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='controller', to='aim.holding')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='holding',
            unique_together={('portfolio', 'symbol')},
        ),
    ]
