# Generated by Django 3.2.4 on 2022-02-21 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aim', '0004_auto_20201230_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('emailed', models.BooleanField(default=False)),
                ('alert', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aim.holdingalert')),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aim.holding')),
            ],
        ),
    ]
