apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "sotb.fullname" . }}
  labels:
    {{- include "sotb.labels" . | nindent 4 }}
spec:
  schedule: "0 23 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            env:
            - name: DATABASE_URL
              valueFrom: { secretKeyRef: { name: sotb-pguser-adminsyymgnc, key: uri } }
            - name: FTPPASS
              valueFrom: { secretKeyRef: { name: investing, key: ftppass } }
            - name: FTPLOGIN
              valueFrom: { secretKeyRef: { name: investing, key: ftplogin } }
            - name: EMAIL_USER
              valueFrom: { secretKeyRef: { name: investing, key: emailuser } }
            - name: EMAIL_PASSWORD
              valueFrom: { secretKeyRef: { name: investing, key: emailpassword } }
            command: ["./loadprices.sh"]

          restartPolicy: OnFailure